# Site settings
title: Home
url: "http://iamzhuoxuan.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
timezone: Asia/Guangzhou
description: >
  记录卓璇的所思所想。
  
# Your information
email: iamzhuoxuan@gmail.com
author: 詹卓璇
avatar: "https://raw.githubusercontent.com/iamzhuoxuan/iamzhuoxuan.github.io/master/img/image0.jpg"
profile: 记录卓璇的所思所想。
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
